lib/expert_advice_web/router.ex
defmodule ExpertAdviceWeb.Router do
  use ExpertAdviceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ExpertAdviceWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExpertAdviceWeb do
    pipe_through :browser

    get "/", PostController, :index
    get "/ask", PostController, :new
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController do
      post "/answer", AnswerController, :create
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExpertAdviceWeb do
  #   pipe_through :api
  # end
end

lib/expert_advice/accounts/post.ex
defmodule ExpertAdvice.Accounts.Post do
  use Ecto.Schema
  import Ecto.Query
  import Ecto.Changeset

  @derive {Phoenix.Param, key: :slug}

  schema "posts" do
    field :title, :string
    field :body, :string
    field :slug, :string
    belongs_to :user, ExpertAdvice.Accounts.User
    belongs_to :post, ExpertAdvice.Accounts.Post
    has_many :answers, ExpertAdvice.Accounts.Post, foreign_key: :post_id
    many_to_many :tags, ExpertAdvice.Accounts.Tag, join_through: "posts_tags"

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
    |> unique_constraint(:title, message: "This question was already asked, make sure your question is unique")
    |> assoc_constraint(:user)
    |> process_slug
  end

  def answer_changeset(post, attrs) do
    post
    |> cast(attrs, [:body])
    |> validate_required([:body])
    |> assoc_constraint(:user)
    |> assoc_constraint(:post)
  end


  defp process_slug(%Ecto.Changeset{valid?: validity, changes: %{title: title}} = changeset) do
    case validity do
      true -> put_change(changeset, :slug, Slugger.slugify_downcase(title))
      false -> changeset
    end
  end

  defp process_slug(changeset), do: changeset

  def newest_question(query, tags) when is_nil(tags) or byte_size(tags) == 0 do
    from q in query, where: is_nil(q.post_id), order_by: [desc: q.inserted_at]
  end

  def newest_question(query, tags) do
    tags = String.split(tags, ", ")
    from q in query,
    preload: [:tags],
    join: tag in assoc(q, :tags),
    group_by: q.id,
    where: tag.name in ^tags,
    where: is_nil(q.post_id),
    order_by: [desc: q.inserted_at]
  end


end

lib/expert_advice_web/controllers/post_controller.ex
defmodule ExpertAdviceWeb.PostController do
  use ExpertAdviceWeb, :controller

  alias ExpertAdvice.Accounts
  alias ExpertAdvice.Accounts.Post

  plug :authenticate_user when action in [:new, :create, :edit, :update, :delete]
  plug :authorize_user when action in [:edit, :update, :delete]

  def index(conn, params, _current_user) do
    tags = get_in(params,["search", "tag"])
    page = Accounts.list_posts(params, tags)
    render(conn, "index.html", posts: page.entries, page: page)
  end

  def new(conn, _params, _current_user) do
    changeset = Accounts.change_post(%Post{})
    render(conn, "new.html", changeset: changeset, tags: [])
  end

  def create(conn, %{"post" =>  %{"tags"=> tags} = post_params}, current_user) do
    case Accounts.create_question(current_user, post_params) do
      {:ok, post} ->
        Accounts.add_tags(post, tags)
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, tags: tags)
    end
  end

  def show(conn, %{"id" => id}, _current_user) do
    post = Accounts.get_post!(id)
    answer_changeset = Accounts.change_answer(%Post{})
    render(conn, "show.html", post: post, answer_changeset: answer_changeset)
  end

  def edit(conn, %{"id" => id}, current_user) do
    post = Accounts.get_user_question!(current_user, id)
    tags = Accounts.tags_loaded(post)
    changeset = Accounts.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset, tags: tags)
  end

  def update(conn, %{"id" => id, "post" => %{"tags"=> tags} = post_params }, current_user) do
    post = Accounts.get_user_question!(current_user, id)
    Accounts.update_tags(post, tags)

    case Accounts.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    post = Accounts.get_user_question!(current_user, id)
    {:ok, _post} = Accounts.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: Routes.post_path(conn, :index))
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  defp authorize_user(conn, _params) do
    %{params: %{"id" => post_id}} = conn
    post = Accounts.get_post!(post_id)

    if conn.assigns.current_user.id == post.user_id do
      conn
    else
      conn
      |> put_flash(:error, "You are not authorized to access that page")
      |> redirect(to: Routes.post_path(conn, :index))
      |> halt()
    end
  end

end

lib/expert_advice_web/views/post_view.ex
defmodule ExpertAdviceWeb.PostView do
  use ExpertAdviceWeb, :view
  import Scrivener.HTML
end

lib/expert_advice_web/templates/post/answer_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>


  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/expert_advice_web/templates/post/edit.html.eex
<h1>Edit Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/expert_advice_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <%= label f, :tag %>
  <%= textarea f, :tags, value: @tags, placeholder: "Add Tags by seperating by commas" %>
  <%= error_tag f, :tags %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/expert_advice_web/templates/post/index.html.eex
<h1>Expert Advice</h1>
<h4>get answers to difficult questions</h4>
<%= form_for @conn, Routes.post_path(@conn, :index), [method: :get, as: :search, class: "form-inline"], fn f -> %>
  <div class="form-group search">
     <%= label(f, :tag, "Search") %>
      <%= text_input(f, :tag, [class: "search-input", placeholder: "Search by tags sperating by commas ex: food, diet, fitness"]) %>
  </div>
   <%= link "Ask a Question", to: Routes.post_path(@conn, :new), class: "btn btn-primary mb-2 ask" %>
  </div>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= link post.title, to: Routes.post_path(@conn, :show, post) %><br>
      <%= for tag <- post.tags do %>
        <span class="label label-primary"><%= tag.name %></span>
      <% end %>
      </td>
      <td>
        <span><%= link "Show", to: Routes.post_path(@conn, :show, post) %></span>
        <%= if @current_user do %>
            <%= if post.user_id == @current_user.id  do %>
              <span><%= link "Edit", to: Routes.post_path(@conn, :edit, post) %></span>
             <span><%= link "Delete", to: Routes.post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"] %></span>
            <% end %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>


<%= pagination_links @page %>

lib/expert_advice_web/templates/post/new.html.eex
<h1>New Question</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/expert_advice_web/templates/post/show.html.eex
<h1>Show Question</h1>

<ul>
  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

</ul>
<h3>Answers</h3>
<ul>
<%= for answer <- @post.answers do %>
  <li class="answer"><%= answer.body %></li>
<% end %>
</ul>
<h3>Add a answer</h3>
<%= form_for @answer_changeset, Routes.post_answer_path(@conn, :create, @post), fn f -> %>
  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>
  <div>
    <%= submit "Save" %>
  </div>
<% end %>
<span><%= link "Edit", to: Routes.post_path(@conn, :edit, @post) %></span>
<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>