lib/expert_advice_web/router.ex
defmodule ExpertAdviceWeb.Router do
  use ExpertAdviceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ExpertAdviceWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExpertAdviceWeb do
    pipe_through :browser

    get "/", PostController, :index
    get "/ask", PostController, :new
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController do
      post "/answer", AnswerController, :create
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExpertAdviceWeb do
  #   pipe_through :api
  # end
end

lib/expert_advice_web/views/layout_view.ex
defmodule ExpertAdviceWeb.LayoutView do
  use ExpertAdviceWeb, :view
end

lib/expert_advice_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Expert Advice · Phoenix Framework</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
    
      <section class="container">
        <nav role="navigation">
          <ul>
          <%= if @current_user do %>
            <li><%= @current_user.name %> | <%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete", class: "main-nav" %></li>
            <% else %>
               <li><%= link "Log in", to: Routes.session_path(@conn, :new), class: "main-nav" %> | <%= link "Register", to: Routes.user_path(@conn, :new), class: "main-nav" %></li>
          <% end %>
          </ul>
        </nav>
        <a href="/" class="main-title" style="font-size: x-large">
          Expert Advice
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>